### ISSUE TITLE
Currency Update Settings

### ISSUE THREAD

**Issue by tv006** [VTTAssets/vtta-dndbeyond#260]
The importer overwrites currency amounts regardless of inventory-related Update settings (Weapons, Equipment, Other inventory items). Would prefer additional toggle, otherwise "Other inventory items" would be a good catch for it.

**Comment by VTTAssets** [comment]
I am very reluctant to provide endless toggles and switches because of user-experience issues and since - from a Foundry standpoint - currency is not an item, your wording would be off. 

I advise to manage on dndbeyond and to play on Foundry. The easy fix would be to update your earnings on dndbeyond after the session in order to have the correct amount on next import.
