### ISSUE TITLE
Character Import Stuck with message "Always prepared spells received, adding them to your import"

### ISSUE THREAD

**Issue by marcabomb** [VTTAssets/vtta-dndbeyond#305]
I was attempting to update a character sheet in my game with new data after a level up and received the message in the title of this post. I also tried making his token from scratch again and was also not working. I am not having this issue with other characters. Looking inside the json console, some field is unrecognized and is stopping the process.

Here is the specific JSON error,
import.js:849 Uncaught (in promise) Error: TypeError: Cannot read property 'name' of undefined
    at CharacterImport.parseCharacterData (import.js:849)
    at import.js:738
parseCharacterData @ import.js:849
(anonymous) @ import.js:738
Promise.then (async)
(anonymous) @ import.js:706
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Here is a link to the character's JSON data.
https://ddb-character.vttassets.com/32000526

I am not sure which field is triggering the issue. As a workaround, I wouldn't mind removing that specific field from the json data but I need help determining which one it is.

Thank you,
Marc

**Comment by DrDougPhD** [comment]
This seems to be an issue with the `componentId` field on some spells offered up through class features. Is your character by chance using new class features from Tasha's?

The error seems to be originating here: https://github.com/VTTAssets/vtta-dndbeyond/blob/master/src/parser/spells/getCharacterSpells.js#L77

"Speak with Animals" and "Beast Sense" have `componentId = 3050148`, but there are no `lookups.classFeature` entries with that `id` in your character JSON.

Not sure of any available workarounds at the moment, but if I come upon something, I'll add another comment.

**Comment by DrDougPhD** [comment]
I'm inclined to think this is a D&D Beyond problem and not one originating in vtta-dndbeyond.

I've encountered this problem with one of my player characters - a Ranger (level 5, https://www.dndbeyond.com/profile/AgentWorm/characters/34581775), but the character does not employ the optional class features from Tasha's Cauldron. This JSON results in the import error reported above: https://gist.github.com/DrDougPhD/2772f3407a6427dafa409efcfd8211b1/2b117c8a24488971b960c80572eed8fe37e3e8cd

Here are two workarounds. I recommend Workaround 1 if your character is not employing Tasha's Cauldron optional class features; otherwise, Workaround 2 may allow Tasha's Cauldron to be temporarily accommodated.

**Workaround 1: Spell Removal**
Remove the "Speak with Animals" and "Beast Sense" spells from the JSON import, like this: https://gist.github.com/DrDougPhD/2772f3407a6427dafa409efcfd8211b1/revisions#diff-e7625274c108e5b447820bcb0a080b8aa816b831d14ca77eca6f7b11086f212c

**Workaround 2: Stubbed Tasha's Class Feature Definition**
Add a stubbed definition for "Primal Awareness" to the array at `data.classes[n].classFeatures`, where `data.classes[n]` is the Ranger class (i.e. data.classes[n].definition.name == "Ranger"`), like so:
https://gist.github.com/DrDougPhD/2772f3407a6427dafa409efcfd8211b1/revisions#diff-280b6d4ed2754ccefcecf31726c493b905ab74c418bc149f47160155736cbfc5

**Comment by DrDougPhD** [comment]
@marcabomb here's a patch to your character sheet that should work. It follows Workaround 1, as it doesn't seem like your character is employing Tasha's Cauldron class features.

Full JSON: https://gist.github.com/DrDougPhD/a9282d0e2de71168f8027676a9edbc7c

Specific patch (spell removal): https://gist.github.com/DrDougPhD/a9282d0e2de71168f8027676a9edbc7c/revisions#diff-257266f1179ffb029683f535b7fa4f9edc37d286bcffbaf3ecaaff06948775bb

**Comment by marcabomb** [comment]
The fixed json worked for me, thank you very much!

**Comment by DrDougPhD** [comment]
I wouldn't close this, as the issue still exists.
